import BottomNavigation from "@/components/layout/BottomNavigation";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { authOptions } from "@/lib/auth";
import { getClient } from "@/lib/client";

import { AppProvider } from "@/modules/common/AppContext";
import ProductReviewModal from "@/modules/product/components/ProductReviewModal";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import "./globals.css";
import { CollectionsQuery, CollectionsDocument } from "@/__generated__/graphql";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  const { data } = await getClient().query<CollectionsQuery>({
    query: CollectionsDocument,
    variables: {
      options: {
        filter: {
          parentId: { eq: "1" },
        },
      },
    },
  });
  return (
    <html lang="en" data-theme="pastel">
      <body className={inter.className}>
        <AppProvider session={session} collections={data.collections.items}>
          <Header />
          {children}
          <BottomNavigation />
          <ProductReviewModal />
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
